config/routes.rb
Rails.application.routes.draw do

  root'home#index'
  resources :tickets
  devise_for :users, controllers: {registrations: "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to tickets_path
  	else
  		redirect_to new_user_session_path
  	end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

      def account_update_params
      	params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
      	
      end
		
	end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:titre, :description, :nom__personne)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

    <% if user_signed_in? %>
    <p>
       Bonjour, <%= current_user.name %>  
        <%= link_to "Log_out", destroy_user_session_path, 'data-turbo-method': :delete %></p>
     <% end %> 
    <%= yield %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titre, style: "display: block" %>
    <%= form.text_field :titre %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :nom__personne, style: "display: block" %>
    <%= form.text_field :nom__personne %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <p>
    <strong>Titre:</strong>
    <%= ticket.titre %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= ticket.description %>
  </p>

  <p>
    <strong>Nom  personne:</strong>
    <%= ticket.nom__personne %>
  </p>

</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>les Tickets</h1>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket %>
    <p>
      <%= link_to "Afficher ce ticket
", ticket %>
    </p>
  <% end %>
</div>

<%= link_to "Nouveau ticket", new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Retour aux tickets", tickets_path %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket %>

<div>
  <%= link_to "Modifier ce  ticket", edit_ticket_path(@ticket) %> |
  <%= link_to "Retour aux tickets
", tickets_path %>
    <br>
  <p><%= button_to "Suprimer ce  ticket", @ticket, method: :delete %></p>
</div>